#!/bin/zsh

# generated by chatgpt https://chatgpt.com/g/g-2DQzU5UZl-code-copilot

# Check if the folder name argument is provided
if [ -z "$1" ]; then
  echo "Usage: $0 <folder-name>"
  exit 1
fi

# Assign the folder name
TARGET_DIR="$1"

# Check if the target directory exists
if [ ! -d "$TARGET_DIR" ]; then
  echo "Error: Directory '$TARGET_DIR' does not exist."
  exit 1
fi

# Create or overwrite the index.ts file
INDEX_FILE="$TARGET_DIR/index.ts"
echo "Debug: Clearing or creating $INDEX_FILE"
: > "$INDEX_FILE" || { echo "Error: Could not write to $INDEX_FILE"; exit 1; }

# Loop through all items in the directory
for ITEM in "$TARGET_DIR"/*; do
  BASENAME=$(basename "$ITEM" .ts) # Strip the .ts extension
  if [ -f "$ITEM" ] && [[ "$ITEM" == *.ts ]] && [ "$BASENAME" != "index" ]; then
    # Export .ts files
    echo "export * from \"./${BASENAME}\"" >> "$INDEX_FILE"
  elif [ -d "$ITEM" ] && [ -f "$ITEM/index.ts" ]; then
    # Export subdirectories explicitly pointing to their index.ts
    DIRNAME=$(basename "$ITEM")
    echo "export * from \"./${DIRNAME}/index\"" >> "$INDEX_FILE"
  fi
done

echo "index.ts has been updated in '$TARGET_DIR'."
